DROP SCHEMA PAYMENT_SYSTEM IF EXISTS CASCADE;

CREATE SCHEMA IF NOT EXISTS PAYMENT_SYSTEM;

CREATE TABLE PAYMENT_SYSTEM.USER (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	FIRST_NAME VARCHAR(255) NOT NULL,
	LAST_NAME VARCHAR(255) NOT NULL,
	CONSTRAINT CONSTRAINT_2 PRIMARY KEY (ID)
) ;

CREATE TABLE PAYMENT_SYSTEM.ACCOUNT (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	ACCOUNT_NUMBER VARCHAR(255) NOT NULL,
	ACCOUNT_STATE VARCHAR(255) NOT NULL,
	BALANCE DECIMAL(19,2) NOT NULL CHECK (BALANCE >= 0),
	CURRENCY_CODE INTEGER NOT NULL,
	USER_ID BIGINT NOT NULL,
	CONSTRAINT CONSTRAINT_E PRIMARY KEY (ID),
	CONSTRAINT FKKQHGXSH08IUVU8SG577I45YBY FOREIGN KEY (USER_ID) REFERENCES PAYMENT_SYSTEM.USER(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;
CREATE UNIQUE INDEX ACCOUNT_ACCOUNT_NUMBER_IX ON PAYMENT_SYSTEM.ACCOUNT (ACCOUNT_NUMBER) ;


CREATE TABLE PAYMENT_SYSTEM.DOCUMENT (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	DESCRIPTION VARCHAR(255),
	DOC_STATUS VARCHAR(255) NOT NULL,
	DOC_TYPE VARCHAR(255) NOT NULL,
	VERSION BIGINT NOT NULL,
	CONSTRAINT CONSTRAINT_6 PRIMARY KEY (ID)
) ;
CREATE INDEX DOCUMENT_DOC_STATUS_IX ON PAYMENT_SYSTEM.DOCUMENT (DOC_STATUS) ;

CREATE TABLE PAYMENT_SYSTEM.ACCOUNT_OPERATION (
	ACCOUNT_OPERATION_TYPE VARCHAR(255) NOT NULL,
	AMOUNT DECIMAL(19,2) NOT NULL CHECK (AMOUNT > 0),
	ID BIGINT NOT NULL,
	ACCOUNT_ID BIGINT NOT NULL,
	CONSTRAINT CONSTRAINT_D PRIMARY KEY (ID),
	CONSTRAINT FK4VTDB8KG2YRMGCY4IIE84B6R7 FOREIGN KEY (ID) REFERENCES PAYMENT_SYSTEM.DOCUMENT(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT FKH5LFBAV42LM0ALD4952TGE8O2 FOREIGN KEY (ACCOUNT_ID) REFERENCES PAYMENT_SYSTEM.ACCOUNT(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;

CREATE TABLE PAYMENT_SYSTEM.PAYMENT (
	AMOUNT DECIMAL(19,2) NOT NULL CHECK (AMOUNT > 0),
	CURRENCY_CODE INTEGER NOT NULL,
	ID BIGINT NOT NULL,
	PAYEE_ID BIGINT NOT NULL,
	PAYER_ID BIGINT NOT NULL,
	CONSTRAINT CONSTRAINT_F PRIMARY KEY (ID),
	CONSTRAINT FK1I6GRWFRFBEDPH14IJ3I5XS6H FOREIGN KEY (ID) REFERENCES PAYMENT_SYSTEM.DOCUMENT(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT FKE795FNOA4XX1VFRGD6S30EMR6 FOREIGN KEY (PAYEE_ID) REFERENCES PAYMENT_SYSTEM.ACCOUNT(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT FKOX6LT799IHXRHQ02HVV3FPVNM FOREIGN KEY (PAYER_ID) REFERENCES PAYMENT_SYSTEM.ACCOUNT(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;